server {
    listen 1024;
    listen [::]:1024 ipv6only=on;
    # listen 443 default_server ssl;
    # listen [::]:443 ipv6only=on;

    # You need to add your SSL certs here
    # ssl_certificate /path/to/mydomain.com.crt;
    # ssl_certificate_key /path/to/mydomain.com.key;
    # ssl_dhparam /path/to/dhparam.pem;

    root /srv/www/localhost/web/wp;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    # location ~ /\.ht {
    #     deny all;
    # }
}